# Generated by Django 4.2.11 on 2024-04-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservations',
            managers=[
            ],
        ),
    ]
